[ERROR] [1617128608.063781, 1951.574000]: bad callback: <bound method SegmentMapper.marker_callback of <__main__.SegmentMapper instance at 0x7fe04b888638>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/pujie/catkin_ws/src/followbot/src/detector/segment_mapper.py", line 90, in marker_callback
    spl = CubicSpline(s, pts, axis=1)
  File "/home/pujie/openmht/2.7/local/lib/python2.7/site-packages/scipy/interpolate/_cubic.py", line 531, in __init__
    raise ValueError("`x` must contain at least 2 elements.")
ValueError: `x` must contain at least 2 elements.

[ERROR] [1617128602.902242, 1948.136000]: bad callback: <bound method SegmentMapper.marker_callback of <__main__.SegmentMapper instance at 0x7fe04b888638>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/pujie/catkin_ws/src/followbot/src/detector/segment_mapper.py", line 67, in marker_callback
    pts = self._msgs_to_odom_frame(self.current_segment)
  File "/home/pujie/catkin_ws/src/followbot/src/detector/segment_mapper.py", line 126, in _msgs_to_odom_frame
    new_pt = self.tfBuffer.transform(PointStamped(m.header, pt), 'odom')
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tf2_ros/buffer_interface.py", line 67, in transform
    object_stamped.header.stamp, timeout))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tf2_ros/buffer.py", line 87, in lookup_transform
    return self.lookup_transform_core(target_frame, source_frame, time)
ExtrapolationException: Lookup would require extrapolation into the future.  Requested time 1948.136000000 but the latest data is at time 1948.135000000, when looking up transform from frame [camera_depth_optical_frame] to frame [odom]
